name: django_app

services:
    app:
      image: djangoapp
      build:
        context: .
      ports:
        - "8000:8000"
      depends_on:
        app-postgres:
          condition: service_healthy
      volumes:
        - "/opt/myapp_static:/static"
        
      restart: always


    app-postgres:
      image: postgres:16-alpine
      ports:
        - "5432:5432"
      volumes:
        - "/opt/myapp_data:/var/lib/postgresql/data"
      environment:
        POSTGRES_DB: django_app
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      healthcheck:
        test: ["CMD-SHELL","pg_isready","-U","postgres"]
        interval: 1s
        timeout: 5s
        retries: 10
      restart: always
